---
- name: Ensure MySQL is installed
  action: apt pkg={{ item }} state=latest
  with_items:
      - mysql-client
      - mysql-server
      - php5-mysql
  notify : restart mysql

- name: service Mysql is started
  service: name=mysql state=started enabled=yes

- name: set our MySQL config my.cnf
  action: template src='mysqld-ansible.cnf.j2' dest='/etc/mysql/conf.d/mysqld-ansible.cnf'
  notify: restart mysql

- name: create root MySQL users
  mysql_user: name={{ mysql.user_root }} password={{ mysql.pass_root }} host={{ item }} state=present
  with_items:
    - "%"
    - "{{ ansible_eth1.ipv4.address }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify: restart mysql

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Create DB "demo"
  mysql_user: name={{ mysql.user }} password={{ mysql.pass }} priv={{ mysql.db }}.*:ALL host={{ item }} state=present
  with_items:
    - "%"
    - "{{ ansible_eth1.ipv4.address }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify: restart mysql

- name: Create DB "test"
  mysql_user: name={{ mysql.user }} password={{ mysql.pass }} priv={{ mysql.db_test }}.*:ALL host={{ item }} state=present
  with_items:
    - "%"
    - "{{ ansible_eth1.ipv4.address }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify: restart mysql

#- name: remove default test MySQL DB
#  mysql_db: name=test state=absent