language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

install:
  - composer self-update && composer --version
  - composer install --prefer-dist
  - composer require satooshi/php-coveralls:*@dev
  - framework/rock.sh

before_script:
  - mysql -e 'CREATE DATABASE rocktest;'

script:
  - mkdir -p build/logs
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      vendor/bin/phpunit --verbose --exclude-group php
    else
      vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml --exclude-group hhvm
    fi

after_script:
  - vendor/bin/coveralls -v