language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

services:
  - rabbitmq

# try running against postgres 9.4
addons:
  postgresql: "9.4"

install:
  - composer self-update && composer --version
  - composer install --prefer-dist
  - composer require satooshi/php-coveralls:*@dev
  - chmod -R +x tests/data/travis/
  - tests/data/travis/zmq-setup.sh
  - tests/data/travis/gearman-setup.sh
  - tests/data/travis/rabbitmq-setup.sh
  - tests/data/travis/image-setup.sh
  #- tests/data/travis/cubrid-setup.sh
  - framework/rock.sh

before_script:
  - mysql -e 'CREATE DATABASE rocktest;'

script:
  - mkdir -p build/logs
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      vendor/bin/phpunit --verbose --exclude-group php,mq
    else
      vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml --exclude-group hhvm
    fi

after_script:
  - vendor/bin/coveralls -v