language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

services:
  - redis-server
  - memcached
  - rabbitmq

install:
  - composer self-update && composer --version
  - composer install --prefer-dist
  - composer require satooshi/php-coveralls:*@dev
  - chmod -R +x tests/data/travis/
  - tests/data/travis/apc-setup.sh
  - tests/data/travis/memcache-setup.sh
  - tests/data/travis/redis-setup.sh
  - tests/data/travis/couchbase-setup.sh
  #- tests/data/travis/zmq-setup.sh
  - tests/data/travis/gearman-setup.sh
#  - tests/data/travis/rabbitmq-setup.sh
  - tests/data/travis/image-setup.sh
  - framework/rock.sh

before_script:
  - mysql -e 'CREATE DATABASE rocktest;';
  - tests/data/travis/sphinx-setup.sh

script:
  - mkdir -p build/logs
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      vendor/bin/phpunit --verbose --exclude-group php,couchbase,memcache,memcached,redis,apc,mq
    else
      vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml --exclude-group hhvm,zeromq,rabbitmq
    fi

after_script:
  - vendor/bin/coveralls -v