language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly

services:
  - redis-server
  - memcached
  - rabbitmq

install:
  - composer self-update && composer --version
  - composer install --prefer-dist
  - composer require satooshi/php-coveralls:*@dev
  - chmod -R +x tests/data/travis/
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then tests/data/travis/apc-setup.sh; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then tests/data/travis/memcache-setup.sh; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then tests/data/travis/redis-setup.sh; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then tests/data/travis/mq-setup.sh; fi;'
  - framework/rock.sh

before_script:
  - mysql -e 'CREATE DATABASE rocktest;';
  - tests/data/travis/sphinx-setup.sh

script:
  - mkdir -p build/logs
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml --exclude-group hhvm,couchbase,zeromq; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] || [ "$TRAVIS_PHP_VERSION" == "hhvm-nightly" ]; then vendor/bin/phpunit --verbose --exclude-group php,couchbase,memcache,memcached,redis,apc,mq; fi;'

after_script:
  - vendor/bin/coveralls -v