- name: download Composer
  shell: creates="composer.phar" chdir="/tmp" curl -s http://getcomposer.org/installer | php

- name: install Composer globally
  shell: creates="/usr/local/bin/composer" chdir="/tmp"  mv composer.phar /usr/local/bin/composer