---
- name: set hostname
  shell: hostname {{ hostname }}

- name: update apt cache
  apt: update_cache=yes

- name: a bit of locale magic
  shell: "{{ item }}"
  with_items:
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8