---
- hosts: vagrant
  sudo: true

  roles:
    - initial
    - common
    - nginx
    - php
    - composer
    - mysql
#    - redis
#    - memcached
#    - couchbase
#    - zeromq
#    - rabbitmq
#    - gearmanmq
    - demo
