hostname: rock

user: vagrant
group: vagrant

php_error_reporting: E_ALL
php_display_errors: On
php_upload_max_filesize: 20M
php_post_max_size: 25M

mysql_root_user: root
mysql_root_pass: root
mysql_user: rock
mysql_pass: rock
mysql_db: rockdemo
mysql_bind_address: 0.0.0.0  # Allows all connections, for Production it should be 127.0.0.1
mysql_key_buffer: 64M

vhosts:
  [
    { name: 'rock', rootFolder: '/var/www/public'}
  ]
